spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl11
    password: pinku
    username: system
    driver-class-name: "oracle.jdbc.OracleDriver"
  jpa:
    
    database: ORACLE
    default_schema: Anil
    spring.jpa.hibernate.generate_ddl: true
    spring.jpa.hibernate.ddl-auto: create    
 
  server:
    port: 9998